permalink: /blog/:year/:title/
gems:
  - jekyll-archives
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layout: archive
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'