permalink: /blog/:year/:title/
collections:
  projects:
    output: true
    layout: post
    permalink: /project/:title/
defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: projects
    values:
      layout: project
gems:
  - jekyll-archives
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layout: archive
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'